DataWrangling/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('DataWranglingApp/', include('DataWranglingApp.urls')),
    path('admin/', admin.site.urls)
]

DataWranglingApp/urls.py
from django.urls import path

from . import views

app_name = 'app'

urlpatterns = [
    path('', views.index, name='index'),
    path('airlines/', views.airlines, name='airlines'),
    path('top/', views.top, name='top'),
]

DataWranglingApp/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class Airlines(models.Model):
    carrier = models.CharField(primary_key=True, max_length=255)
    name = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'Airlines'

    def __str__(self):
            return self.name

class Airports(models.Model):
    faa = models.CharField(primary_key=True, max_length=255)
    name = models.CharField(max_length=255)
    lat = models.CharField(max_length=255)
    lon = models.CharField(max_length=255)
    alt = models.IntegerField()
    tz = models.IntegerField()
    dst = models.CharField(max_length=255)
    tzone = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'Airports'


class Flights(models.Model):
    year = models.IntegerField()
    month = models.IntegerField()
    day = models.IntegerField()
    dep_time = models.IntegerField()
    flight = models.IntegerField()
    origin = models.ForeignKey(Airports, models.DO_NOTHING, db_column='origin')
    dest = models.CharField(max_length=255)
    schd_dep_time = models.IntegerField()
    dep_delay = models.IntegerField()
    arr_time = models.IntegerField()
    sched_arr_time = models.IntegerField()
    arr_delay = models.IntegerField()
    carrier = models.ForeignKey(Airlines, models.DO_NOTHING, db_column='carrier')
    tailnum = models.CharField(max_length=255)
    air_time = models.IntegerField()
    distance = models.IntegerField()
    hour = models.IntegerField()
    minute = models.IntegerField()
    time_hour = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'Flights'


class Planes(models.Model):
    tailnum = models.CharField(primary_key=True, max_length=255)
    year = models.IntegerField()
    type = models.CharField(max_length=255)
    manufacturer = models.CharField(max_length=255)
    model = models.CharField(max_length=255)
    engines = models.IntegerField()
    seats = models.IntegerField()
    speed = models.CharField(max_length=255)
    engine = models.CharField(max_length=255)

    class Meta:
        managed = False
        db_table = 'Planes'


class Weather(models.Model):
    origin = models.OneToOneField(Airports, models.DO_NOTHING, db_column='origin', primary_key=True)
    year = models.IntegerField()
    day = models.IntegerField()
    hour = models.IntegerField()
    temp = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    dewp = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    humid = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    wind_dir = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    wind_speed = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    wind_gust = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    precip = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    pressure = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    visib = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    time_hour = models.DateTimeField()
    month = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'Weather'
        unique_together = (('origin', 'year', 'day', 'hour', 'month'),)


class WeatherWith3Doublons(models.Model):
    origin = models.OneToOneField(Airports, models.DO_NOTHING, db_column='origin', primary_key=True)
    year = models.IntegerField()
    month = models.IntegerField()
    day = models.IntegerField()
    hour = models.IntegerField()
    temp = models.DecimalField(max_digits=10, decimal_places=0)
    dewp = models.DecimalField(max_digits=10, decimal_places=0)
    humid = models.DecimalField(max_digits=10, decimal_places=0)
    wind_dir = models.IntegerField(blank=True, null=True)
    wind_speed = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    wind_gust = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    precip = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    pressure = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    visib = models.DecimalField(max_digits=10, decimal_places=0, blank=True, null=True)
    time_hour = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'Weather_with_3_doublons'
        unique_together = (('origin', 'year', 'month', 'day', 'hour'),)


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=150)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=150)
    last_name = models.CharField(max_length=150)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.PositiveSmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'

DataWranglingApp/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from DataWranglingApp.models import Airlines, Flights

def index(request):
    return HttpResponse("Hello, world. You're at the polls index.")

def airlines(request):
    template = loader.get_template('airlines.html')

    airlines = Airlines.objects.all()

    context = {
        'objects': airlines
    }

    return HttpResponse(template.render(context))

def top(request):
    template = loader.get_template('top.html')

    top_dest = Flights.objects.raw("SELECT 1 id, a.name AS dest, COUNT(*) AS total FROM `Flights` f INNER JOIN `Airports` a ON f.dest = a.faa GROUP BY dest ORDER BY COUNT(*) DESC")[:10]
    top_origin = Flights.objects.raw("SELECT 1 id, a.name AS ogn, COUNT(*) AS total FROM `Flights` f INNER JOIN `Airports` a ON f.origin = a.faa GROUP BY origin ORDER BY COUNT(*) DESC")[:10]

    context = {
        'top_dest': top_dest,
        'top_origin': top_origin
    }

    return HttpResponse(template.render(context))

DataWranglingApp/templates/airlines.html
{% extends "base.html" %}

{% block content %}

<h1>Airlines</h1>

<table class="table">
    <tr>
        <th>Carrier</th>
        <th>Name</th>
    </tr>
    {% for object in objects %}
    <tr>
        <td>{{ object.carrier }}</td>
        <td>{{ object.name }}</td>
    </tr>
    {% endfor %}
</table>
<!--
<div class="pagination">
        <span class="step-links">
            {% if object_list.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ contacts.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ object_list.number }} of {{ object_list.paginator.num_pages }}.
            </span>

            {% if object_list.has_next %}
                <a href="?page={{ object_list.next_page_number }}">next</a>
                <a href="?page={{ object_list.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
</div>
-->
{% endblock %}

DataWranglingApp/templates/base.html
<!DOCTYPE html>
{% load static %}

<html lang="fr">
<head>
    <meta charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
<nav class="navbar navbar-expand-sm bg-dark navbar-dark">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" href="{% url 'app:airlines' %}">Airlines</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" href="{% url 'app:top' %}">Top</a>
        </li>
    </ul>
</nav>
    <div class="container">
        {% block content %} {% endblock %}
    </div>
    {% block js %}{% endblock%}
</body>

</html>

DataWranglingApp/templates/top.html
{% extends "base.html" %}

{% block content %}

<h1>Top 10 destinations</h1>

<table class="table">
    <tr>
        <th>Destination</th>
        <th class="text-right">Nb flights</th>
    </tr>
    {% for object in top_dest %}
    <tr>
        <td>{{ object.dest }}</td>
        <td class="text-right">{{ object.total }}</td>
    </tr>
    {% endfor %}
</table>

<h1>Top 3 origins</h1>

<table class="table">
    <tr>
        <th>Origin</th>
        <th class="text-right">Nb flights</th>
    </tr>
    {% for object in top_origin %}
    <tr>
        <td>{{ object.ogn }}</td>
        <td class="text-right">{{ object.total }}</td>
    </tr>
    {% endfor %}
</table>

{% endblock %}